export const SAMPLE_SHOWCASE_ITEMS = [
  {
    id: 'sample-showcase-electric',
    isSample: true,
    title: 'Temiz elektrik panosu kurulumu',
    description: 'Düzenli kablolama ve güvenli sigorta yerleşimi için örnek çalışma.',
    image: require('../assets/images/v_vitrin_elektrik.jpg'),
    images: [require('../assets/images/v_vitrin_elektrik.jpg')],
    ustaName: 'İş Bitir Usta Vitrini',
    ustaCity: 'Örnek çalışma',
  },
  {
    id: 'sample-showcase-plumbing',
    isSample: true,
    title: 'Tesisat yenileme çalışması',
    description: 'Ustaların tamamladığı işlerin nasıl sergileneceğini gösteren örnek.',
    image: require('../assets/images/v_vitrin_tesisat.jpg'),
    images: [require('../assets/images/v_vitrin_tesisat.jpg')],
    ustaName: 'İş Bitir Usta Vitrini',
    ustaCity: 'Örnek çalışma',
  },
  {
    id: 'sample-showcase-aircon',
    isSample: true,
    title: 'Klima bakım ve montajı',
    description: 'Hüner kaydı oluşturulduğunda bu örneklerin yerini gerçek çalışmalar alır.',
    image: require('../assets/images/v_vitrin_klima.jpg'),
    images: [require('../assets/images/v_vitrin_klima.jpg')],
    ustaName: 'İş Bitir Usta Vitrini',
    ustaCity: 'Örnek çalışma',
  },
];

export const SAMPLE_MARKETPLACE_PRODUCTS = [
  {
    id: 'sample-marketplace-cable',
    isSample: true,
    title: 'Elektrik kablosu',
    desc: 'Pazar yeri ilanlarının görünümünü gösteren örnek ürün.',
    price: 950,
    category: 'Kablo & Tesisat',
    location: 'Örnek ilan',
    sellerName: 'İş Bitir Pazar Yeri',
    sellerType: 'ELECTRICIAN',
    sellerId: 'sample-seller',
    image: require('../assets/images/mock_hes_kablo.jpg'),
    images: [require('../assets/images/mock_hes_kablo.jpg')],
    date: 'Örnek',
    isSold: false,
  },
  {
    id: 'sample-marketplace-breaker',
    isSample: true,
    title: 'Otomatik sigorta',
    desc: 'Gerçek bir ürün yayınlandığında örnek ilanlar otomatik olarak kaldırılır.',
    price: 425,
    category: 'Şalt Malzemesi',
    location: 'Örnek ilan',
    sellerName: 'İş Bitir Pazar Yeri',
    sellerType: 'ELECTRICIAN',
    sellerId: 'sample-seller',
    image: require('../assets/images/mock_siemens_sigorta.jpg'),
    images: [require('../assets/images/mock_siemens_sigorta.jpg')],
    date: 'Örnek',
    isSold: false,
  },
];
