import LegalPage from '@/components/LegalPage';
import { legalIdentity } from '@/constants/legal';

export const metadata = { title: 'KVKK Aydınlatma Metni', description: 'İşBitir kişisel veri işleme faaliyetlerine ilişkin aydınlatma metni.', robots: legalIdentity.ready ? undefined : { index: false, follow: false } };

export default function KvkkPage() {
  return <LegalPage title="KVKK Aydınlatma Metni" description="İşBitir web sitesi ve mobil uygulamalarındaki kişisel veri işleme faaliyetleri hakkında bilgilendirme.">
    <section><h2>1. Veri sorumlusu</h2><p>6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) kapsamında veri sorumlusu <strong>{legalIdentity.entityName}</strong>’dir. Adres: {legalIdentity.address}. KVKK başvuruları için: <a href={`mailto:${legalIdentity.legalEmail}`}>{legalIdentity.legalEmail}</a>.</p></section>
    <section><h2>2. İşlenen kişisel veriler</h2><ul><li>Kimlik ve iletişim: ad, soyad, telefon, hesap ve oturum tanımlayıcıları.</li><li>Hizmet talebi: kategori, açıklama, zamanlama tercihi, teklif ve işlem kayıtları.</li><li>Konum: kullanıcının yazdığı il, ilçe, mahalle, adres ve izin vermesi hâlinde yaklaşık cihaz koordinatı.</li><li>İşlem güvenliği: oturum, tarih-saat, hata, güvenlik ve kötüye kullanım önleme kayıtları.</li><li>Usta profili: uzmanlık, hizmet bölgesi, belge/onay durumu, değerlendirme ve iş geçmişi.</li></ul></section>
    <section><h2>3. İşleme amaçları ve hukuki sebepler</h2><p>Veriler; talebin oluşturulması ve takibi, uygun ustalara yönlendirme, teklif ve iletişim akışının yürütülmesi, sözleşme süreçleri, destek, bilgi güvenliği, uyuşmazlık yönetimi ve yasal yükümlülüklerin yerine getirilmesi amaçlarıyla işlenir. İşleme; sözleşmenin kurulması veya ifası, hukuki yükümlülük, bir hakkın tesisi/kullanılması/korunması ve temel haklara zarar vermemek kaydıyla meşru menfaat sebeplerine dayanabilir. Açık rıza gereken ayrı bir faaliyet varsa ayrıca ve özgür iradeyle alınır.</p></section>
    <section><h2>4. Aktarım ve alıcı grupları</h2><p>Talep bilgileri, işin niteliği ve hizmet bölgesiyle sınırlı olarak eşleşen ustalara gösterilebilir. Telefon numarası teklif aşamasında gösterilmez; teklif kabul edildiğinde seçilen usta ile iletişim kurulması amacıyla erişilebilir hâle gelir. Veriler ayrıca barındırma, kimlik doğrulama, veritabanı, güvenlik ve bildirim hizmeti sağlayıcılarına; hukuki zorunluluk hâlinde yetkili kamu kurumlarına ve uyuşmazlık taraflarına aktarılabilir.</p><p>Yurt dışı altyapı veya hizmet sağlayıcısı kullanılması hâlinde aktarım, KVKK’nın yurt dışına aktarım hükümlerindeki uygun güvence veya istisna şartları doğrulanarak gerçekleştirilmelidir. Canlı ortam sağlayıcıları ve veri bölgeleri yayın öncesi hukuk ve güvenlik incelemesinden geçirilir.</p></section>
    <section><h2>5. Toplama yöntemi</h2><p>Veriler; web ve mobil formlar, cihaz izinleri, kullanıcı işlemleri, destek kanalları ve sistem güvenliği kayıtları üzerinden otomatik veya kısmen otomatik yöntemlerle toplanır. Cihaz konumu yalnızca tarayıcı/işletim sistemi izniyle alınır; il ve ilçe elle de girilebilir.</p></section>
    <section><h2>6. Saklama ve silme</h2><p>Veriler işleme amacı ve ilgili yasal süre boyunca saklanır; süre sonunda silinir, yok edilir veya anonim hâle getirilir. Web üzerinden oluşturulan taleplere ait ayrı iletişim kaydı için teknik varsayılan saklama süresi 180 gündür; devam eden uyuşmazlık veya yasal yükümlülük varsa ilgili kayıt gerekli süreyle sınırlı olarak tutulabilir.</p></section>
    <section><h2>7. İlgili kişinin hakları</h2><p>KVKK’nın 11. maddesi kapsamındaki haklarınız çerçevesinde verinizin işlenip işlenmediğini öğrenme, bilgi isteme, amacına uygun kullanımı öğrenme, aktarılan üçüncü kişileri bilme, düzeltme, silme/yok etme isteme, bu işlemlerin aktarılan kişilere bildirilmesini isteme, otomatik analiz sonucuna itiraz ve zararın giderilmesini talep etme haklarına sahipsiniz.</p></section>
    <section><h2>8. Başvuru</h2><p>Kimliğinizi ve talebinizi açıkça belirterek {legalIdentity.address} adresine veya <a href={`mailto:${legalIdentity.legalEmail}`}>{legalIdentity.legalEmail}</a> e-posta adresine başvurabilirsiniz. Güvenli başvuru yöntemleri ve varsa KEP adresi, işletme bilgileri kesinleştirildiğinde ayrıca yayımlanmalıdır.</p></section>
  </LegalPage>;
}
