import { supabase } from './supabase';
export interface CalendarEvent { id:string; userId:string; title:string; note?:string; eventDate:string; eventTime?:string; hasReminder:boolean; reminderAt?:string; reminderSentAt?:string; amount?:number; isPaid:boolean; status:string; createdAt:string; updatedAt:string; }
const map=(r:any):CalendarEvent=>({id:r.id,userId:r.user_id,title:r.title,note:r.note,eventDate:r.event_date,eventTime:r.event_time,hasReminder:r.has_reminder,reminderAt:r.reminder_at,reminderSentAt:r.reminder_sent_at,amount:r.amount==null?undefined:Number(r.amount),isPaid:r.is_paid,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at});
const uid=async()=>{const {data}=await supabase.auth.getUser();if(!data.user)throw new Error('Oturum bulunamadı.');return data.user.id;};
export const calendarService={
 async getEvents(month?:number,year?:number){let q=supabase.from('calendar_events').select('*').eq('user_id',await uid()).order('event_date');if(month&&year){const from=new Date(year,month-1,1).toISOString(),to=new Date(year,month,1).toISOString();q=q.gte('event_date',from).lt('event_date',to);}const {data,error}=await q;if(error)throw error;return(data||[]).map(map);},
 async createEvent(d:any){const userId=await uid();const {data,error}=await supabase.from('calendar_events').insert({user_id:userId,title:d.title,note:d.note||null,event_date:d.eventDate,event_time:d.eventTime||null,has_reminder:!!d.hasReminder,reminder_at:d.reminderAt||null,amount:d.amount??null}).select().single();if(error)throw error;return map(data);},
 async updateEvent(id:string,d:any){const updates:any={};for(const [a,b] of Object.entries({title:'title',note:'note',eventDate:'event_date',eventTime:'event_time',hasReminder:'has_reminder',reminderAt:'reminder_at',amount:'amount',isPaid:'is_paid',status:'status'})){if(d[a]!==undefined)updates[b]=d[a];}const {data,error}=await supabase.from('calendar_events').update(updates).eq('id',id).select().single();if(error)throw error;return map(data);},
 async completeEvent(id:string,addToLedger?:boolean){const {data,error}=await supabase.rpc('complete_calendar_event',{event_id:id,add_to_ledger:!!addToLedger});if(error)throw error;return map(data);},
 async deleteEvent(id:string){const {error}=await supabase.from('calendar_events').delete().eq('id',id);if(error)throw error;return true;}
};
