import { supabase } from './supabase';
export interface LedgerEntry{id:string;userId:string;personName:string;amount:number;type:'receivable'|'payable';status:'pending'|'paid';note?:string;dueDate?:string;paidAt?:string;calendarEventId?:string;eventTime?:string;hasReminder?:boolean;reminderAt?:string;reminderSentAt?:string;createdAt:string;updatedAt:string;}
export interface LedgerSummary{pendingReceivables:number;pendingPayables:number;totalReceived:number;totalPaid:number;netBalance:number;}
const map=(r:any):LedgerEntry=>({id:r.id,userId:r.user_id,personName:r.person_name,amount:Number(r.amount),type:r.type,status:r.status,note:r.note,dueDate:r.due_date,paidAt:r.paid_at,calendarEventId:r.calendar_event_id,eventTime:r.event_time,hasReminder:r.has_reminder,reminderAt:r.reminder_at,reminderSentAt:r.reminder_sent_at,createdAt:r.created_at,updatedAt:r.updated_at});
const uid=async()=>{const {data}=await supabase.auth.getUser();if(!data.user)throw new Error('Oturum bulunamadı.');return data.user.id;};
export const ledgerService={
 async getEntries(type?:string,status?:string){let q=supabase.from('ledger_entries').select('*').eq('user_id',await uid()).order('created_at',{ascending:false});if(type)q=q.eq('type',type);if(status)q=q.eq('status',status);const {data,error}=await q;if(error)throw error;return(data||[]).map(map);},
 async getSummary(){const rows=await this.getEntries();const s={pendingReceivables:0,pendingPayables:0,totalReceived:0,totalPaid:0,netBalance:0};for(const r of rows){if(r.type==='receivable'&&r.status==='pending')s.pendingReceivables+=r.amount;if(r.type==='payable'&&r.status==='pending')s.pendingPayables+=r.amount;if(r.type==='receivable'&&r.status==='paid')s.totalReceived+=r.amount;if(r.type==='payable'&&r.status==='paid')s.totalPaid+=r.amount;}s.netBalance=s.pendingReceivables-s.pendingPayables;return s;},
 async createEntry(d:any){const {data,error}=await supabase.from('ledger_entries').insert({user_id:await uid(),person_name:d.personName,amount:d.amount,type:d.type,note:d.note||null,due_date:d.dueDate||null,event_time:d.eventTime||null,has_reminder:!!d.hasReminder,reminder_at:d.reminderAt||null}).select().single();if(error)throw error;return map(data);},
 async updateEntry(id:string,d:any){const u:any={};for(const[a,b]of Object.entries({personName:'person_name',amount:'amount',type:'type',status:'status',note:'note',dueDate:'due_date',eventTime:'event_time',hasReminder:'has_reminder',reminderAt:'reminder_at'})){if(d[a]!==undefined)u[b]=d[a];}const {data,error}=await supabase.from('ledger_entries').update(u).eq('id',id).select().single();if(error)throw error;return map(data);},
 async togglePaid(id:string){const {data:old,error:e}=await supabase.from('ledger_entries').select('*').eq('id',id).single();if(e)throw e;const paid=old.status!=='paid';const {data,error}=await supabase.from('ledger_entries').update({status:paid?'paid':'pending',paid_at:paid?new Date().toISOString():null}).eq('id',id).select().single();if(error)throw error;return map(data);},
 async deleteEntry(id:string){const {error}=await supabase.from('ledger_entries').delete().eq('id',id);if(error)throw error;return true;}
};
