import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Check, QrCode, Smartphone } from 'lucide-react';
import { APP_STORE_URL, GOOGLE_PLAY_URL } from '@/constants/storeLinks';

export default function AppDownload() {
  return (
    <section id="uygulama-indir" className="scroll-mt-24 overflow-hidden bg-[linear-gradient(135deg,#020617,#0f172a_55%,#134e4a)] py-20 text-white sm:py-24">
      <div className="mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8">
        <div><span className="inline-flex items-center gap-2 rounded-full border border-teal-400/20 bg-teal-400/10 px-3 py-1 text-xs font-bold text-teal-300"><Smartphone className="h-3.5 w-3.5" /> Ustalar için mobil uygulama</span><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-5xl">Hizmet bölgenizdeki uygun talepleri mobil uygulamadan yönetin.</h2><p className="mt-5 max-w-xl text-base leading-7 text-slate-300">Usta profili, hizmet bölgesi, müsaitlik ve belge süreçleri uygulama üzerinden yönetilir. Eşleşen yeni talepler için bildirim alabilir, teklifinizi uygulamadan iletebilirsiniz.</p><ul className="mt-7 space-y-3 text-sm text-slate-300">{['Bildirim ve teklif yönetimi', 'Hizmet bölgesi ve müsaitlik ayarları', 'Profil, belge ve iş geçmişi ekranları'].map((item) => <li key={item} className="flex items-center gap-3"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-teal-400/15 text-teal-300"><Check className="h-3.5 w-3.5" /></span>{item}</li>)}</ul><div className="mt-8 flex flex-wrap gap-3"><a href={GOOGLE_PLAY_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-950 transition hover:bg-teal-50">Google Play&apos;den indir <ArrowRight className="h-4 w-4" /></a>{APP_STORE_URL ? <a href={APP_STORE_URL} target="_blank" rel="noopener noreferrer" className="rounded-xl border border-white/15 bg-white/10 px-5 py-3 text-sm font-bold text-white">App Store</a> : <span className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold text-slate-300">iOS uygulaması yakında</span>}<Link href="/usta-kayit" className="rounded-xl border border-teal-300/30 px-5 py-3 text-sm font-bold text-teal-200">Usta sürecini incele</Link></div></div>
        <div className="relative mx-auto w-full max-w-md"><div className="absolute inset-8 rounded-full bg-teal-400/20 blur-3xl" /><div className="relative rounded-[2rem] border border-white/10 bg-white/[0.07] p-6 shadow-2xl backdrop-blur sm:p-8"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-teal-400/10 text-teal-300"><QrCode className="h-5 w-5" /></span><div><h3 className="font-bold">Telefonunuza indirin</h3><p className="text-xs text-slate-400">Android için Google Play</p></div></div><div className="mt-6 hidden items-center gap-6 rounded-2xl bg-white p-5 text-slate-950 sm:flex"><Image src="/google-play-qr.png" width={168} height={168} alt="İşBitir Google Play indirme bağlantısı QR kodu" unoptimized className="h-36 w-36 rounded-lg" /><div><p className="font-black">Kameranızla okutun</p><p className="mt-2 text-sm leading-6 text-slate-600">Telefon kameranızı QR koda tutun, çıkan bağlantıya dokunun ve İşBitir sayfasını Google Play&apos;de açın.</p></div></div><ol className="mt-6 grid gap-3 text-sm text-slate-300 sm:hidden"><li><strong className="text-white">1.</strong> Google Play düğmesine dokunun.</li><li><strong className="text-white">2.</strong> Mağazada uygulama adını ve geliştiriciyi kontrol edin.</li><li><strong className="text-white">3.</strong> Google Play üzerinden yükleyin.</li></ol><p className="mt-5 text-xs leading-5 text-slate-500">QR kod ve düğme aynı resmî Google Play sayfasına yönlendirir. iOS sürümü henüz yayımlanmadı.</p></div></div>
      </div>
    </section>
  );
}
